### ISSUE TITLE
Porting archive new items from aiida.net

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-website#13]
Found at https://www.aiida.net/wp-admin/edit.php?post_type=news

Tick off / add, what you do/are working on:

- @giovannipizzi 
  - [x] AiiDA v1.3.0 released
- @mbercx
  - [x] Documentation revamp, and more than 50 registered plugins
- @ramirezfranciscof 
  - [x] Newly-engineered Materials Cloud Archive
- @csadorf
  - [ ] 2020 Questionnaire results – AiiDA papers & testimonials
- @unkcpz 
  - [x] AiiDA v1.2.0 released

**Comment by ramirezfranciscof** [comment]
I'm PR-ing my assignment, will check it when all issues are resolved.

I will continue with all news post from the year 2022 (except for the releases and if there is any of the posts assigned in this OP, if any). I think it will be easier to avoid overlapping if we take full years (or months if some year was very active), and we let others know beforehand here.
