### ISSUE TITLE
Update Twitter Logo Across Documentation Page

### ISSUE THREAD

**Issue by SharanRP** [aiidateam/aiida-website#59]
![image](https://github.com/aiidateam/aiida-website/assets/136159249/5cfc9344-aa39-48c4-a813-f07877fb54c2)

I've noticed that the Twitter logo used across the documentation page seems to be outdated. As per the Twitter Brand Guidelines, we should be using the most current version of the logo.

If you agree that this is a valid issue, I would be more than happy to work on it and submit a pull request.

**Comment by eimrek** [comment]
thanks @SharanRP! Yes, would be nice to get this fixed! Although the docs themselves are built from the [aiida-core](https://github.com/aiidateam/aiida-core) repository, so you would have to make a PR there.
